// lib/fonts.js
//
// Loads the Latin face via next/font/google and the CJK face from the
// locally generated frequency-tiered subset (see scripts/build-cjk-subset.mjs).
// Exposes them as CSS variables --font-latin and --font-cjk.
//
// Usage in app/layout.jsx:
//   import { fontLatin, fontCJK } from '@/lib/fonts'
//
//   <html className={`${fontLatin.variable} ${fontCJK.variable}`}>
//
// Both variables are referenced in tailwind.config.js and globals.css.
// Neither font is set as the default className — that's intentional.
// The CSS variable approach lets Tailwind's fontFamily tokens and
// the :lang(zh) rule in globals.css each pull the right face without
// Next.js injecting a global className that would create specificity fights.
//
// Bilingual note: the :lang(zh) rule in globals.css and Tailwind's
// font-cjk token both resolve through --font-cjk, which the generated
// stylesheet sets. Adding Chinese copy needs no change in this file —
// but DOES need `npm run fonts:cjk` if it introduces new characters.
// The build guard will tell you.

import { Source_Sans_3 } from 'next/font/google'

// ── Source Sans 3 — all English content (D59) ─────────────────
// Replaced DM Sans. This is not a taste change — it fixes a real bug.
//
// Noto Sans SC below IS Source Han Sans (same typeface, two release
// names), and its Latin glyphs are Source Sans, scaled to 115% to sit
// correctly beside Chinese. Pairing it with DM Sans meant Latin inside
// Chinese copy rendered in Source Sans while the SAME words on the
// English site rendered in DM Sans — measured at 122px vs 119px for
// "Lexile 187 DODO" at 16px. Two Latin designs for one brand, split by
// locale. Using Source Sans 3 here makes both scripts agree, because it
// is the face the CJK font was drawn to sit beside.
//
// Weights: 300 (captions), 400 (body), 500 (medium), 600 (semibold), 700 (display)
// Italic: loaded for body and medium weights only — display italics are rare
// subsets: latin covers the full EN character set including diacritics
//   for student and Navigator names (accented Latin chars common in diaspora families)
export const fontLatin = Source_Sans_3({
  subsets: ['latin', 'latin-ext'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: '--font-latin',
  display: 'swap',
  // preload: true is the default — Next.js will <link rel="preload"> this font.
  // The Latin face is used above the fold (nav, hero headline), so preload is correct.
  preload: true,
  fallback: [
    'system-ui',
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Helvetica Neue',
    'Arial',
    'sans-serif',
  ],
  // adjustFontFallback: true injects a @font-face fallback with size-adjust,
  // ascent-override, descent-override tuned to reduce CLS during font swap.
  adjustFontFallback: true,
})

// ── CJK — frequency-tiered local subset (Noto Sans SC) ────────
// Was: Noto_Sans_SC() from next/font/google. Replaced because the hosted
// version splits by unicode-range into ~101 chunks PER WEIGHT — 303
// @font-face declarations, 13.2 MB declared — and a Chinese page pulled
// 23 of them: 1,090 KB measured cold on /zh/faq.
//
// The replacement subsets the real character set of this site (1,574
// CJK characters incl. punctuation and fullwidth forms) into 5
// frequency-ordered chunks totalling 437 KB across the whole 400–700
// weight range, because the source is a VARIABLE font — one file per
// chunk serves every weight instead of one file per weight per range.
//
// The @font-face rules live in styles/cjk-fonts.css, GENERATED by
// scripts/build-cjk-subset.mjs. They are not written here because
// next/font/local cannot express a per-chunk unicode-range — its src
// entries take only { path, weight, style } — and unicode-range is the
// entire mechanism. See that script's header for the full rationale.
//
// Regenerate after adding Chinese copy:   npm run fonts:cjk
// The prebuild/postbuild guard tells you when that is due.
//
// D62 (ZH adopts LXGW WenKai GB) rides on this pipeline: it is a
// --source flag on the generator, not a rewrite here.

// Kept in sync with CJK_FAMILY / CJK_VAR_CLASS in scripts/build-cjk-subset.mjs.
export const CJK_FAMILY = 'DODO CJK Subset'

// Shaped like a next/font return value so app/layout.jsx keeps working
// unchanged: it still spreads `fontCJK.variable` onto <html>, and the
// class (defined in the generated stylesheet) sets --font-cjk. Every
// downstream consumer — globals.css :lang(zh), the Tailwind font-cjk
// token — reads that variable and is untouched by this change.
export const fontCJK = {
  variable: 'font-cjk-subset',
  className: 'font-cjk-subset',
  style: { fontFamily: `'${CJK_FAMILY}', 'PingFang SC', 'Hiragino Sans GB', sans-serif` },
}
